trigger:
  branches:
    include:
    - master

pr: none

stages:
- stage: Build
  displayName: Build WAR

  jobs:
  - job: BuildJob
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'package'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.11'
        jdkArchitectureOption: 'x64'

    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)'
        Contents: '**/*.war'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'java-war-file'
        publishLocation: 'Container'

- stage: Deploy
  displayName: Deploy WAR
  dependsOn: Build

  jobs:
  - deployment: DeployToVM
    displayName: Deploy To Windows VM

    environment:
      name: 'java_webapp'
      resourceName: 'sunkari'
      resourceType: VirtualMachine

    strategy:
      runOnce:
        deploy:
          steps:

          - download: current
            artifact: java-war-file

          - task: PowerShell@2
            displayName: 'Deploy WAR to Tomcat'
            inputs:
              targetType: 'inline'
              script: |

                Write-Host "===== MACHINE INFO ====="
                hostname
                Write-Host $env:COMPUTERNAME
                Write-Host $env:OS

                Get-ChildItem -Path "$(Pipeline.Workspace)" -Recurse

                $war = Get-ChildItem `
                  -Path "$(Pipeline.Workspace)" `
                  -Filter *.war `
                  -Recurse | Select-Object -First 1

                if ($null -eq $war) {
                  throw "WAR file not found"
                }

                Write-Host "WAR Found: $($war.FullName)"

                $TomcatWebApps = "C:\Program Files\Tomact\webapps"

                if (!(Test-Path $TomcatWebApps)) {
                  throw "Tomcat path not found: $TomcatWebApps"
                }

                Copy-Item `
                  -Path $war.FullName `
                  -Destination "$TomcatWebApps\webapp.war" `
                  -Force

                Write-Host "WAR copied successfully"

                Get-ChildItem "$TomcatWebApps"