trigger:
- master

stages:

- stage: Build
  jobs:
  - job: Build
    pool:
      vmImage: ubuntu-latest

    steps:

    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        mavenOptions: '-Xmx3072m'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.11'
        jdkArchitectureOption: 'x64'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        goals: 'package'

    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)'
        Contents: '**/*.war'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'java-war-file'
        publishLocation: 'Container'

- stage: Deploy
  dependsOn: Build

  jobs:
  - deployment: DeployToVM
    environment: java_webapp

    strategy:
      runOnce:
        deploy:
          steps:

          - download: current
            artifact: java-war-file

          - powershell: |
              Write-Host "Deployment reached VM successfully"
              hostname

              # Show downloaded files
              Get-ChildItem -Recurse "$(Pipeline.Workspace)"

              # Find WAR file
              $war = Get-ChildItem -Path "$(Pipeline.Workspace)" -Filter *.war -Recurse | Select-Object -First 1

              Write-Host "WAR file found: $($war.FullName)"

              # Copy WAR to Tomcat webapps folder
              Copy-Item $war.FullName `
                "C:\Users\sunkari\Downloads\apache-tomcat-9.0.121-windows-x64\apache-tomcat-9.0.121\webapps\" `
                -Force

              Write-Host "WAR copied successfully"