trigger: none
pr: none

pool:
  name: CorpMachine

steps:
# 1. Build the Application
- task: Maven@3
  displayName: 'Build Java Application'
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'package'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'Path'
    jdkDirectory: '/usr/lib/jvm/java-21-openjdk-amd64'
    jdkArchitectureOption: 'x64'
    mavenVersionOption: 'Default'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
- task: CopyFiles@2
  displayName: 'Staging WAR File'
  inputs:
    Contents: '**/*.war'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'localWebapp'
    publishLocation: 'Container'
- script: |
    echo "========================================="
    echo "1. DEPLOYING WAR FILE TO TOMCAT CONTAINER..."
    # Moves out of the agent build workspace folder and drops it straight into Tomcat
    cp "$(System.DefaultWorkingDirectory)/webapp/target/webapp.war" "$(System.DefaultWorkingDirectory)/../../../apache/tomcat/webapps/"

    echo "========================================="
    echo "2. VERIFYING TOMCAT DEPLOYMENT LOCATION:"
    ls -l "$(System.DefaultWorkingDirectory)/../../../apache/tomcat/webapps/webapp.war"
  displayName: 'Deploy WAR to Local Tomcat'
